### ISSUE TITLE
Makefile is broken...

### ISSUE THREAD

**Issue by WacKEDmaN** [sammyizimmy/ili9341#4]
when running make i get this error...
```
pi@raspberrypi:~/ili9341 $ make
make -C /lib/modules/4.19.75-v7+/build M= modules
make[1]: *** /lib/modules/4.19.75-v7+/build: No such file or directory.  Stop.
make: *** [Makefile:4: all] Error 2

```
the /build folder doesnt exist... so i add it...
now i get this error..
```
pi@raspberrypi:~/ili9341 $ make
make -C /lib/modules/4.19.75-v7+/build M=/home/pi/ili9341 modules
make[1]: Entering directory '/lib/modules/4.19.75-v7+/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/lib/modules/4.19.75-v7+/build'
make: *** [Makefile:4: all] Error 2
```

any help would be greatly appreciated!

**Comment by j-m-harris** [comment]
You need the kernel headers to compile, don't create the build dir yourself.

e.g. on debian:
`apt-get install linux-headers`

**Comment by WacKEDmaN** [comment]
only a year late!...moved on to a SPI screen!

**Comment by j-m-harris** [comment]
Hah, sorry! Just ran into this myself.
Perhaps will help someone else in future at least. :)

**Comment by MrLeafster** [comment]
@j-m-harris  Hi, can you help me with making this work? I successfully build it with your fix, but I can't get "sudo insmod ili9341.ko" command to work, I'm getting "Segmentation fault" or it just hangs... I'm not that skilled with kernels, so I would appreciate if you could assist me.

**Comment by j-m-harris** [comment]
@MrLeafster Sorry, I did not run into that problem! Which kernel are you using?

**Comment by MrLeafster** [comment]
@j-m-harris Thank you for responding! The problem was hidden in bcm2708_peri_base. The address was wrong for the Raspberry Pi 3b+. It's fixed now.

I have another question... I see some green edges around some objects on screen such as text and icons. Is there a way to remove them?

**Comment by j-m-harris** [comment]
@MrLeafster Glad you got it working, congrats on working it out.

I didn't see any green edges on mine, example output at: https://github.com/j-m-harris/ili9341/blob/master/lcd_on.jpg
That's ported to a 16bit transfer mode on a 'TFT_320QDT_9341' screen though, I think there are lots of screens using this controller.
