### ISSUE TITLE
Getting "Segmentation fault"

### ISSUE THREAD

**Issue by MrLeafster** [sammyizimmy/ili9341#6]
I'm trying to use the library, and I succeeded in running "make" command, but when I want to run "sudo inmod ili9341.ko" I'm getting "Segmentation fault"? And when I run it for the 2nd time it just doesn't give any output, it's just stuck... Can someone plz help...

**Comment by j-m-harris** [comment]
@MrLeafster said this was due to BCM2708_PERI_BASE- ensure this is set correctly per device.

```
// 0x20000000 on the Pi Zero, Pi Zero W, and the first generation of the Raspberry Pi
// Differs on later pis, check docs at:
// https://www.raspberrypi.org/documentation/hardware/raspberrypi/peripheral_addresses.md
#define BCM2708_PERI_BASE        0x20000000
```
